"0":  "送金処理を継続するために、トークンに送金先口座の上4桁と送金額の上2桁を入力して下さい。"
"1":  "送金処理を継続するために、トークンに送金先口座の下4桁と送金額の下2桁を入力して下さい。"
"2":  "送金処理を継続するために、トークンに送金先口座の上4桁と送金額の下2桁を入力して下さい。"
"3":  "送金処理を継続するために、トークンに送金先口座の下4桁と送金額の上2桁を入力して下さい。"
"4":  "送金処理を継続するために、トークンでQRコードの読み取りを実施して下さい。"
