"6009":  "セキュリテリコードの値が合っていないですね・・・もう一回!"
"600B":  "Credential ID をキチンと入力して下さい。"
"600D":  "お使いのトークンがロックもしくは使えない状態ですね。"
"6004":  "存在しない Credential ID です。"
"6011":  "1ユーザで利用可能なトークンは5つまでです。"
"6012":  "1ユーザで利用可能なトークンは5つまでです。"
"6015":  "入力した文字列が不正です。"
"49B5":  "チャレンジに対するレスポンスの値が合ってないですね・・・"
